AS = as --32
LD = ld
LDFLAGS = -m elf_i386
CC = gcc
OBJCOPY = objcopy
OBJDUMP = objdump
STRIP = strip
CFLAGS  = -g -m32 -fno-builtin -fno-stack-protector -fomit-frame-pointer -fstrength-reduce #-Wall
CPP	= cpp -nostdinc

