AS = as --32
LD = ld
LDFLAGS = -m elf_i386
OBJCOPY = objcopy
OBJDUMP = objdump
STRIP = strip
CFLAGS  = -g -m32 -no-pie -fno-pic -gdwarf-2 -fno-builtin -fno-stack-protector -fomit-frame-pointer -fstrength-reduce #-Wall
AR	= ar

